services:
  - type: web
    name: cotizador-app
    env: python
    buildCommand: |
      apt-get update && 
      apt-get install -y libreoffice fonts-liberation fontconfig &&
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: PORT
        value: 5000